//allprojects {
//    buildDir = "../build"
//}

subprojects {
	apply plugin: 'java'
	java.withSourcesJar()
	java.withJavadocJar()

	repositories {
		maven {
			name = 'Forge'
			url = 'https://maven.minecraftforge.net/'
		}
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}

	sourceSets {
		main {
			resources {
				srcDir project(':modules:common').file('src/main/resources')
			}
		}
	}

	if (project.name.startsWith("forge")) {
		tasks.withType(Javadoc).configureEach {
			enabled = false
		}
	}
}