# Mod Properties

# Recommended Versioning Scheme: https://docs.neoforged.net/docs/gettingstarted/versioning/
version = 21.1.0
mod_version=1.3
mc_version=mc1.21.1
minecraft_version_range=[1.21.1, 1.21.2)

# Your mod id should be descriptive, ideally just your mod's name in all lowercase with no hyphens or underscores.
mod_id = survivalfly

mod_name = Survival Fly

# Your group should be a unique identifier in reverse domain format.
group = net.dillon.survivalfly

description=Adds a /flight command for survival players.

# Fill out these URLs with links to your website or project page, sources (if public), issue tracker and Discord invite.
homepage = https://modrinth.com/mod/survival-fly
sources = https://github.com/Dillon8775/Survival-Fly
issues = https://github.com/Dillon8775/Survival-Fly/issues
discord = https://discord.gg/vfqEAn4YFy

# Make sure the license here matches the one you defined in the LICENSE file.
license=All Rights Reserved.

logo=assets/survivalfly/icon

mod_author = Dillon8775

# Credits can include other attribution as well, such as artists, etc.
credits = Dillon8775

# Publishing Properties
# You can find the project ID on the CurseForge / Modrinth project page. You can leave this empty until you publish your mod.
curseforge_project_id = 1275791
modrinth_project_id = Sj7HGYie

# If you have a Maven to deploy to, configure its URLs here.
# maven_releases = https://
# maven_snapshots = https://

# Balm version
balm_version = 26.1.0.6

# Build Properties
# The Java version to use. Different Minecraft versions require different Java versions.
java_version = 21

# You can develop against published NeoForge snapshots (instead of releases) by adding the URL linked in the NeoForge PR here and updating the NeoForge version in gradle/libs.versions.toml.
neoforge_snapshot_url =

# NeoForge version range
neoforge_loader_version_range=[1,)

# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false