# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
mod_id=survivalfly
mod_version=1.3.2
mod_name=Survival Fly
description=Adds a /flight command for survival players.
mod_author=Dillon8775
credits=Dillon8775
license=All rights reserved unless explicitly stated.
logo=assets/survivalfly/icon
mc_version=mc26.1.x
supported_mc_versions=26.1,26.1.1,26.1.2
minecraft_version_range=[26.1, 26.2)
group=net.dillon.survivalfly

# Links
homepage=https://modrinth.com/mod/survival-fly
sources=https://github.com/Dillon8775/Survival-Fly
issues=https://github.com/Dillon8775/Survival-Fly/issues
discord=https://discord.gg/vfqEAn4YFy

# Common
java_version=25
minecraft_version=26.1.2

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# Balm version
balm_version=26.1.0.6

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.145.4+26.1.2
fabric_loader_version=0.18.6
modmenu_version=18.0.0-alpha.6
fabric_permissions_api=0.7.0
luckperms_api=5.4

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.0.1-beta
neoforge_loader_version_range=[4,)

# YetAnotherConfigLib
yacl_version=3.9.3
yalc_mc=26.1

# Other (not required in multiloader-common.gradle)
curseforge_project_id=1279479
modrinth_project_id=R03iLZxe
changelog_file=current_changelog.md

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false