# Every field here must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
mod_id=survivalfly
mod_version=1.3.6
mod_name=Survival Fly
description=A Fabric/(Neo)Forge mod that lets server owners allow players to fly in survival mode.
mod_author=Dillon8775
credits=Dillon8775
license=All rights reserved unless explicitly stated.
logo=assets/survivalfly/icon
mc_version=mc26.3
supported_mc_versions=26.3
# Use "-alpha.# for snapshots
minecraft_version_range=>=26.3-pre.3 <26.4
group=net.dillon.survivalfly

# Links
homepage=https://modrinth.com/mod/survival-fly
sources=https://github.com/Dillon8775/Survival-Fly
issues=https://github.com/Dillon8775/Survival-Fly/issues
discord=https://discord.gg/vfqEAn4YFy

# Common
java_version=25
minecraft_version=26.3-pre-3
devauth_enabled=1

## This is the version of Minecraft that the 'common' directory uses
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.3-pre-3-1

# Dependencies
## Balm
### https://maven.twelveiterations.com/service/rest/repository/browse/maven-public/net/blay09/mods/balm-common/
balm_version=26.3.0.1-SNAPSHOT
## DillonLib
### https://modrinth.com/mod/dillon-lib/versions
dillonlib_version=1.1
## Mod Menu
### https://modrinth.com/mod/modmenu/versions
modmenu_version=21.0.0-alpha.1
## YetAnotherConfigLib (YACL)
### https://maven.isxander.dev/web/releases/dev/isxander/yet-another-config-lib/
yacl_version=3.9.6+26.3
## DevAuth
### https://modrinth.com/mod/dev-auth-neo/versions
devauth_neo_version=1.1.1
## Fabric Permissions API
### https://central.sonatype.com/artifact/me.lucko/fabric-permissions-api/versions
fabric_permissions_api_version=0.7.0
## LuckPerms
luckperms_version=5.5
### https://mvnrepository.com/artifact/net.luckperms/api

# Fabric
## https://fabricmc.net/develop/
fabric_version=0.160.1+26.3
fabric_loader_version=0.19.5

# NeoForge
## https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.0-beta
neoforge_loader_version_range=[4,)

# Other (not required in multiloader-common.gradle)
curseforge_project_id=1279479
modrinth_project_id=R03iLZxe
changelog_file=current_changelog.md

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false