pluginManagement {
	repositories {
		gradlePluginPortal()
		maven {
			name = 'MinecraftForge'
			url = 'https://maven.minecraftforge.net'
		}
		maven {
			name = 'Parchment'
			url = 'https://maven.parchmentmc.org'
		}
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
	}
}

rootProject.name = 'Survival Fly'

// === COMMON ===
include "modules:common"

// === FABRIC ===
include "modules:fabric-mc1.21.9x"
include "modules:fabric-mc1.21.11"

// === FORGE ===
include "modules:forge-mc1.20.1"
include "modules:forge-mc1.21.1"
include "modules:forge-mc1.21.9x"
include "modules:forge-mc1.21.11"

// ----------

// You can add as many modules as you want, for this copy the content of "example_module" to each new module!
//include "modules:example_module"

// Example how to use multiple modules within a module:

// include "modules:MODULE_NAME",
//      "modules:MODULE_NAME:SUB_MODULE_NAME",
//      "modules:MODULE_NAME:SUB_MODULE_NAME"

// You can even add a Multi-Loader project ! (using Architectury may require some extra steps)

//include "modules:multiproject_module",
//        "modules:multiproject_module:common",
//        "modules:multiproject_module:fabric",
//        "modules:multiproject_module:forge"