dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.4'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.4'

    implementation("net.blay09.mods:balm-common:${balm_version}") {
        changing = balm_version.endsWith('SNAPSHOT')
    }

    compileOnly "net.dillon.dillonlib:dillonlib-common-mc26.3:unspecified"
//    compileOnly ("dev.isxander:yet-another-config-lib:${project.yacl_version}-fabric") {
//        transitive = false
//    }
}