dependencies {
    implementation("net.blay09.mods:balm-neoforge:${balm_version}") {
        changing = balm_version.contains('SNAPSHOT')
    }

    compileOnly "net.luckperms:api:${luckperms_api}"

    implementation "dev.isxander:yet-another-config-lib:${project.yacl_version}+${project.yalc_mc}-neoforge"

    implementation "maven.modrinth:dillon-lib:${project.mc_version}-${project.dillonlib_version}-neoforge"
}