dependencies {
    implementation("net.blay09.mods:balm-neoforge:${balm_version}") {
        changing = balm_version.contains('SNAPSHOT')
    }

    // implementation "dev.isxander:yet-another-config-lib:${project.yacl_version}-neoforge"
    implementation "net.dillon.dillonlib:dillonlib-neoforge-mc26.3:unspecified"

    compileOnly "net.luckperms:api:${luckperms_version}"

    runtimeOnly "net.dillon.qualityofqueso:qualityofqueso-neoforge-mc26.3:unspecified"
    runtimeOnly "net.dillon.simplekeybinds:simplekeybinds-neoforge-mc26.3:unspecified"
}